<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
<meta name="keywords" content="<?=$this->lang['meta']['keywords']?>" />
<meta name="description" content="<?=$this->lang['meta']['description']?>" />
<link rel="stylesheet" href="<?=$this->path['css']?>frontend/main.css" type="text/css" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />
<!--[if IE]>
    <link rel="stylesheet" type="text/css" href="<?=$this->path['css']?>frontend/all-ie.css" />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="<?=$this->path['js']?>library/index.js"></script>
<script type="text/javascript" src="<?=$this->path['js']?>tooltip.js"></script>
<script type="text/javascript" src="<?=$this->path['js']?>jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="<?=$this->path['js']?>jquery.corner.js"></script>
<script type="text/javascript" src="<?=$this->path['js']?>modules/Common/scripts.js"></script>
<?php $this->includeJsModule()?>
<?=$this->getHelper('Html_Title')->getHtml()?>
</head><body>
<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div class="content">

<h2 class="header"><?=$this->getHelper('Html_Title')->getByIndex(1)?></h2>

<? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

<?php if (!$this->current_user->isGuest()): ?>
<ul id="my_actions">
    <li style="list-style-image:url('<?=$this->path->image->desing->icon?>advert_add.png');">
        <a href="/my/adverts/edit/">создать новое объявление</a>
    </li>
    <li style="list-style-image:url('<?=$this->path->image->desing->icon?>advert_edit.png');">
        <a href="/my/adverts/">управлять созданными ранее объявлениями</a>
    </li>
    <li style="list-style-image:url('<?=$this->path->image->desing->icon?>advert_user.png');">
        <a href="/my/info/">управлять личной информацией</a>
    </li>
    <li style="list-style-image:url('<?=$this->path->image->desing->icon?>advert_exit.png');">
        <a onclick="return confirm('Вы действительно хотите завершить работу с сайтом?')" href="/logout/?referer=<?=$this->urlencode_full_request_uri?>">завершить работу с сайтом</a>
    </li>
</ul>
<?php endif; ?>

</div>

<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>
</body></html>