<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru" dir="ltr">
<head>
<?=$this->getHelper('Html_Title')->getHtml()?>
<meta http-equiv="Content-language" content="ru" />
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
<link rel="stylesheet" href="/http/css/backend/main.css" type="text/css" />
<script type="text/javascript" src="/http/js/library/index.js"></script>
</head><body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<form id="<?=$this->_module_name?>_<?=$this->_controller_name?>" method="post" action="<?=$this->hsc_request_uri?>">
<table class="aTable">
    <colgroup>
        <col width="30%" />
        <col width="70%" />
    </colgroup>
    <tr>
        <th colspan="2"><h4>
            <? if($this->category->getId()): ?>
                Редактирование категории <?=$this->getHelper('Helper_Format')->hsc($this->category->getName())?>
            <? else: ?>
                Добавление категории
            <? endif; ?></h4>
        </th>
    </tr>
    <tr>
        <td><strong class="compulsory">Категория активна:</strong></td>
        <td>
        <?
        $select = $this->getHelper('Helper_Form')->inputSelect('category[active]', $this->category->getActive());
        $select->addOption( $this->getHelper('Helper_Form')->inputOption(1, $this->lang->yes) );
        $select->addOption( $this->getHelper('Helper_Form')->inputOption(0, $this->lang->no) );
        echo $select->getHtml();
        ?><?=$this->getHelper('Helper_Form')->getFieldError($this->err->active)?>
        </td>
    </tr>
    <tr>
        <td><strong class="compulsory">Родительский узел:</strong></td>
        <td><?
            $select = $this->getHelper('Helper_Form')->inputSelect('category[pid]', $this->category->getPid());
            $select->addOption( $this->getHelper('Helper_Form')->inputOption('0', 'Новый узел') );
            $categories = $this->getHelper('Module_Category_Helper_BackendSelect', $this->tree)->getHtml();
            foreach ($categories as $option):
                $select->addOption($option);
            endforeach;
            echo $select->getHtml();
            ?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->pid)?></td>
    </tr>
    <tr>
        <td><strong class="compulsory">Имя категории:</strong></td>
        <td><?=$this->getHelper('Helper_Form')->inputText('category[name]', $this->category->getName(), array('maxlength'=>255, 'class'=>'textSmall'))->getHtml()?>
           <?=$this->getHelper('Helper_Form')->getFieldError($this->err->name)?></td>
    </tr>
    <tr>
        <td><strong class="compulsory">URL категории:</strong></td>
        <td><?=$this->getHelper('Helper_Form')->inputText('category[alias]', $this->category->getAlias(), array('maxlength'=>255, 'class'=>'textSmall'))->getHtml()?>
           <?=$this->getHelper('Helper_Form')->getFieldError($this->err->alias)?></td>
    </tr>
    <tr>
        <td><strong class="compulsory">Описание категории:</strong></td>
        <td><?=$this->getHelper('Helper_Form')->inputTextarea('category[description]', $this->category->getDescription(), array('class'=>''))->getHtml()?>
           <?=$this->getHelper('Helper_Form')->getFieldError($this->err->description)?></td>
    </tr>
     <tr>
        <td><strong class="compulsory">Ключевые слова:</strong></td>
        <td><?=$this->getHelper('Helper_Form')->inputTextarea('category[keywords]', $this->category->getKeywords(), array('class'=>''))->getHtml()?>
           <?=$this->getHelper('Helper_Form')->getFieldError($this->err->keywords)?></td>
    </tr>
    <tr align="center">
        <td colspan="2">
        <?=$this->getHelper('Helper_Form')->inputHidden('category[id]', $this->category->getId())->getHtml()?>
        <?=$this->getHelper('Helper_Form')->inputSubmit('submit', $this->lang->save_changes)->getHtml()?>&nbsp;&nbsp;&nbsp;
        <?=$this->getHelper('Helper_Form')->inputFullCheckbox('return_on_page', 1, 0, $this->return_on_page, array('id'=>'label_return_on_page'))?>
        &nbsp;<?=$this->getHelper('Helper_Form')->Label($this->lang->return_to_this_page, 'label_return_on_page')->getHtml()?>
        </td>
    </tr>
</table></form>
</body></html>