<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
<meta name="keywords" content="<?=$this->lang['meta']['keywords']?>" />
<meta name="description" content="<?=$this->lang['meta']['description']?>" />
<link rel="stylesheet" href="/http/css/frontend/main.css" type="text/css" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />
<!--[if IE]>
    <link rel="stylesheet" type="text/css" href="/http/css/frontend/all-ie.css" />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="/http/js/tooltip.js"></script>
<script type="text/javascript" src="/http/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/http/js/jquery.corner.js"></script>
<script type="text/javascript" src="/http/js/modules/common/scripts.js"></script>
<?=$this->getHelper('Html_Title')->add('Нужны деньги? Продайте ненужное!')->getHtml()?>
</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div class="content">
<? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <h2 class="header">Нужны деньги? Продайте ненужное!</h2>

    <article id="help">
		<p>Удивительно, но мало кто из нас задумывается об окружающих нас вещах. Среднестатистическая квартира современного человека изобилует множеством вещей, вещей нужных, постоянно используемых, используемых чуть реже и подчас не используемых вообще. Последние могут годами лежать на антресолях и балконах, пылиться в шкафах и комодах, стареть морально и физически, но при этом иметь вполне товарный вид. Так зачем годами хранить то, что по стечению обстоятельств не используется в быту? Зачем ждать, пока вещи естественным образам придут в негодность и отправятся на помойку?</p>

		<h3>Если вещь не использовалась ни разу в течение года, значит, её можно смело... продать!</h3>

		<p>Наверное, все знают негласное правило, гласящее, что если какая-то вещь не используется в быту в течение года или двух, то от неё смело можно избавляться. Как ни странно, многие об этой мудрости банально забывают, после чего квартира превращается в склад:</p>

		<ul>
		    <li>шкафы содержат вполне новую, но не подошедшую или не понравившуюся по тем или иным причинам одежду</li>
		    <li>устаревающая бытовая техника (например, видеомагнитофоны на VHS носителях) годами мешаются и перетаскиваются с места на место</li>
		    <li>ненужная мебель используется в качестве тумбочек или подставок</li>
		    <li>и т.д.</li>
		</ul>

		<p>Перечислять примеры подобного отношения к ненужным вещам можно очень долго. В итоге получается парадоксальная ситуация, когда «нажитое непосильным трудом» имеется, а толку от этого &mdash; нет, только один вред, в виде постоянно увеличивающегося количества хлама. Есть ли из этого выход? Есть &mdash;</p>

		<h3>Подать объявление о продаже</h3>

		<p>Продавать ненужное &mdash; экономически <em>выгодно</em> для семейного бюджета. Посмотрите вокруг себя, что в вашем быту стало лишним? Наверняка где-то имеется купленная несколько лет назад вещь, занимающая место, но не используемая уже долгое время. Не важно, что она не нужна вам, важно то, что она наверняка <em>нужна кому-то другому</em>, причем, быть может, нужна очень сильно. Оцените примерную стоимость вашей вещи и <a href="/add.xhtml">разместите объявление о продаже</a> этого товара. И вскоре наверняка найдется покупатель, готовый приехать и купить то, что для вас давно не имеет никакой ценности.</p>

		<p><strong>Сайт бесплатных объявлений</strong> <a class="text_logo_cover" href="http://www.adverts.ru/"><span class="tl_a">a</span><span class="tl_d">d</span><span class="tl_v">v</span><span class="tl_e">e</span><span class="tl_r">r</span><span class="tl_t">t</span><span class="tl_s">s</span><span class="tl_dot">.</span><span class="tl_r2">r</span><span class="tl_u">u</span></a> предлагает вам размещать объявления о купли-продажи всего того, что можно продать или купить. На нашем сайте можно разместить объявление о продаже недвижимости, объявления о продаже автомобилей, бытовой и компьютерной технике, объявления о продаже предметов коллекционного спроса, домашних животных, растений и многое другое. Кроме того, на сайте есть раздел Услуги, где всегда можно найти специалистов в разных сферах.</p>

		<p>В отличие от других подобных сайтов, на сайте <a class="text_logo_cover" href="http://www.adverts.ru/"><span class="tl_a">a</span><span class="tl_d">d</span><span class="tl_v">v</span><span class="tl_e">e</span><span class="tl_r">r</span><span class="tl_t">t</span><span class="tl_s">s</span><span class="tl_dot">.</span><span class="tl_r2">r</span><span class="tl_u">u</span></a> <strong>объявления размещаются абсолютно бесплатно</strong>.</p>
    </article>
</div>
<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>
</body></html>