<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru" dir="ltr">
<head>
<?=$this->getHelper('Html_Title')->getHtml()?>
<meta http-equiv="Content-language" content="ru" />
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
<link rel="stylesheet" href="/http/css/backend/main.css" type="text/css" />
<script type="text/javascript" src="/http/js/library/index.js"></script>
<script type="text/javascript" src="/http/js/library/locations.js"></script>
</head><body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<form id="<?=$this->_module_name?>_<?=$this->_controller_name?>" method="post" action="<?=$this->hsc_request_uri?>">

<table class="aTable">
    <colgroup>
        <col width="30%" />
        <col width="70%" />
    </colgroup>
    <tr>
        <th colspan="2"><h4>
            <? if($this->user->getId()): ?>
                <?=$this->lang->editing_user?> <?=$this->getHelper('Helper_Format')->hsc($this->user->getFullName())?>
            <? else: ?>
                <?=$this->lang->add_user?>
            <? endif; ?></h4>
        </th>
    </tr>
    <tr>
        <td><strong class="compulsory"><?=$this->lang->user_active?>:</strong></td>
        <td>
        <?
        $select = $this->getHelper('Helper_Form')->inputSelect('user[active]', $this->user->getActive());
        $select->addOption( $this->getHelper('Helper_Form')->inputOption(1, $this->lang->yes) );
        $select->addOption( $this->getHelper('Helper_Form')->inputOption(0, $this->lang->no) );
        echo $select->getHtml();
        ?><?=$this->getHelper('Helper_Form')->getFieldError($this->err->active)?>
        </td>
    </tr>
    <tr>
        <td><?=$this->lang->user_group?>:</td>
        <td><?
            $select = $this->getHelper('Helper_Form')->inputSelect('user[group]', $this->user->getGroup());
            $select->addOption( $this->getHelper('Helper_Form')->inputOption(0, $this->lang->select_value) );
            foreach ($this->groups as $group):
                $select->addOption( $this->getHelper('Helper_Form')->inputOption($group->getId(), $group->getName()) );
            endforeach;
            echo $select->getHtml();
            ?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->group)?></td>
    </tr>

<? if ($this->user->getId()): ?>
    <tr>
        <td><?=$this->lang->id_user?>:</td><td><?=$this->user->getId()?></td>
    </tr>
<? endif; ?>

<? if ($this->user->getIp()): ?>
    <tr>
        <td><?=$this->lang->user_ip?>:</td><td><?=$this->user->getIp()?></td>
    </tr>
<? endif; ?>

<? if ($this->user->getRegdate()): ?>
    <tr>
        <td><?=$this->lang->user_regdate?>:</td>
        <td><?=$this->getHelper('Helper_Form')->inputText('user[regdate]', $this->user->getRegdate()->format('d.m.Y H:i:s'), array('class' => 'textSmall'))->getHtml()?>
        </td>
    </tr>
<? endif; ?>

<? if ($this->user->getVisitdate()): ?>
    <tr>
        <td><?=$this->lang->user_visitdate?>:</td>
        <td><?=$this->getHelper('Helper_Form')->inputText('user[visitdate]', $this->user->getVisitdate()->format('d.m.Y H:i:s'), array('class' => 'textSmall'))->getHtml()?></td>
    </tr>
<? endif; ?>

    <tr>
        <td><strong class="compulsory"><?=$this->lang->user_login?>:</strong></td>
        <td><?=$this->getHelper('Helper_Form')->inputText('user[login]', $this->user->getLogin(), array('maxlength'=>255, 'class'=>'textSmall'))->getHtml()?>
            <? if($this->user->getId()): ?>
                <div><small><?=$this->lang->attention_change_user_login?></small></div>
           <? endif; ?>
           <?=$this->getHelper('Helper_Form')->getFieldError($this->err->login)?></td>
    </tr>

    <tr>
        <td><strong class="compulsory"><?=$this->lang->user_password_1?>:</strong></td>
        <td><?=$this->getHelper('Helper_Form')->inputText('user[password_1]', $this->password_1, array('maxlength'=>255, 'class'=>'textSmall', 'id' => 'user_password_1'))->getHtml()?> <a href="#" onclick="return star2chars('user_password_1', this)">скрыть пароль</a>
            <? if($this->user->id): ?>
                <div><small><?=$this->lang->attention_change_user_password?><br /><br /><?=$this->lang->do_not_fill_this_field?></small></div>
            <? endif; ?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->password_1)?>
        </td>
    </tr>

    <tr>
        <td><strong class="compulsory"><?=$this->lang->user_password_2?>:</strong></td>
        <td><?=$this->getHelper('Helper_Form')->inputText('user[password_2]', $this->password_2, array('maxlength'=>255, 'class'=>'textSmall', 'id' => 'user_password_2'))->getHtml()?> <a href="#" onclick="return star2chars('user_password_2', this)">скрыть пароль</a>
            <? if($this->user->id): ?>
                <div><small><?=$this->lang->do_not_fill_this_field?></small></div>
            <? endif; ?>
             <?=$this->getHelper('Helper_Form')->getFieldError($this->err->password_2)?>
             <?=$this->getHelper('Helper_Form')->getFieldError($this->err->password)?>
        </td>
    </tr>

    <tr>
        <td><strong class="compulsory"><?=$this->lang->user_mail?>:</strong></td>
        <td><?=$this->getHelper('Helper_Form')->inputText('user[mail]', $this->user->getMail()->getValue(), array('maxlength'=>255, 'class'=>'textSmall'))->getHtml()?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->mail)?></td>
    </tr>
    <tr>
        <td><strong class="compulsory"><?=$this->lang->user_first_name?>:</strong></td>
        <td><?=$this->getHelper('Helper_Form')->inputText('user[first_name]', $this->user->getFirstName(), array('maxlength'=>30,
                                                       'class'=>'textSmall',
                                                       'onkeyup' => 'this.value = this.value.ucfirst()'
                                                      ))->getHtml()?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->first_name)?></td>
    </tr>
    <tr>
        <td><?=$this->lang->user_last_name?>:</td>
        <td><?=$this->getHelper('Helper_Form')->inputText('user[last_name]', $this->user->getLastName(), array('maxlength'=>30,
                                                                 'class'=>'medium',
                                                                 'onkeyup' => 'this.value = this.value.ucfirst()'
                                                                ))->getHtml()?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->last_name)?></td>
    </tr>

    <tr>
        <td><strong class="compulsory"><?=$this->lang->user_age?>:</strong></td>
        <td><?=$this->getHelper('Helper_Form')->inputSelectIntegerValues('user[age_day]', 1, 31, $this->user->getAgeDay())->getHtml()?>

            <? $select = $this->getHelper('Helper_Form')->inputSelect('user[age_month]', $this->user->getAgeMonth());
               $select->addOption( $this->getHelper('Helper_Form')->inputOption(0, '') );
               foreach ($this->lang->months_genitive as $key => $value):
                   $select->addOption( $this->getHelper('Helper_Form')->inputOption($key, $value) );
               endforeach;
            ?>
            <?=$select->getHtml();?>

            <?=$this->getHelper('Helper_Form')->inputSelectYears('user[age_year]', $this->user->getAgeYear())->getHtml()?>

            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->age)?>
        </td>
    </tr>

    <tr>
        <td><strong class="compulsory"><?=$this->lang->user_sex?>:</strong></td>
        <td>
        <?php foreach ($this->sex_types as $sex_key => $sex_value): ?>
            <?=$this->getHelper('Helper_Form')->inputRadio('user[sex]', $sex_key, $this->user->getSex()->getValue(), array('id'=>'user_sex_' . $sex_key))->getHtml()?> <?=$this->getHelper('Helper_Form')->Label($sex_value, 'user_sex_' . $sex_key)->getHtml()?>
            &nbsp;
        <?php endforeach; ?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->sex)?>
        </td>
    </tr>

    <tr>
        <td><strong class="compulsory"><?=$this->lang->locations?>:</strong></td>
        <td>
            <div class="form_element_block">
            <? $select = $this->getHelper('Helper_Form')->inputSelect('user[country]', $this->user->getCountry(),
                                                        array('onchange'=>'locations_next_operation(this)', 'id'=>'country')
                                                       );
               $select->addOption( $this->getHelper('Helper_Form')->inputOption(0, $this->lang->select_your_country) );
            ?>
            <?=$select->getHtml();?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->country)?>
            </div>

            <div class="form_element_block">
            <? $select = $this->getHelper('Helper_Form')->inputSelect('user[region]', $this->user->getRegion(),
                                                        array('onchange'=>'locations_next_operation(this)', 'id'=>'region')
                                                       );
               $select->addOption( $this->getHelper('Helper_Form')->inputOption(0, $this->lang->select_your_region.
                                                                     ' ('.$this->lang->select_your_country.')') );
            ?>
            <?=$select->getHtml();?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->region)?>
            </div>
            <div>
            <?
            $select = $this->getHelper('Helper_Form')->inputSelect('user[city]', $this->user->getCity(), array('onchange'=>'locations_next_operation(this)', 'id'=>'city'));
            $select->addOption( $this->getHelper('Helper_Form')->inputOption(0, $this->lang->select_your_city.' ('.$this->lang->select_your_region.')') );
            echo $select->getHtml();
            ?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->city)?></div>
        </td>
    </tr>
    <?php if (0):?>
    <tr>
        <td>Телефоны:</td>
        <td>
            <table class="intoTable">
            <tr>
                <th>Тип телефона</th>
                <th>Номер телефона</th>
                <th>Первичный</th>
                <th>Оптимальное время для звонка</th>
            </tr>
            <? foreach($this->lang->phones_types as $id => $phone_type_name): ?>
                <tr>
                    <td><?=$phone_type_name?>
                        <?=$this->getHelper('Helper_Form')->inputHidden('user[user_phone]['.$id.'][id_type]', $id)->getHtml()?>
                        <?=$this->getHelper('Helper_Form')->inputHidden('user[user_phone]['.$id.'][id_user]',
                                                          ($this->user->user_phone->item($id)
                                                          ? $this->user->user_phone->item($id)->id_user
                                                          : null)
                                                          )->getHtml()?>
                        <?=$this->getHelper('Helper_Form')->inputHidden('user[user_phone]['.$id.'][id]',
                                                          ($this->user->user_phone->$id
                                                          ? $this->user->user_phone->$id->id
                                                          : null))->getHtml()?>
                    </td>
                    <td><?=$this->getHelper('Helper_Form')->inputText('user[user_phone]['.$id.'][phone_number]',
                                                        $this->user->user_phone->$id
                                                        ? $this->user->user_phone->$id->phone_number
                                                        : null)->getHtml()?></td>
                    <td class="center"><?=$this->getHelper('Helper_Form')->inputFullCheckbox('user[user_phone]['.$id.'][phone_primary]', 1, 0,
                                                                $this->user->user_phone->$id
                                                                ? $this->user->user_phone->$id->phone_primary
                                                                : null,
                                                                array('onclick'=>'emulationRadioForCheckboxes(this, this.className)',
                                                                      'class'=>'emulationRadio')
                                                                     )?></td>
                    <td><?=$this->getHelper('Helper_Form')->inputText('user[user_phone]['.$id.'][phone_time_call]',
                                                        $this->user->user_phone->$id
                                                        ? $this->user->user_phone->$id->phone_time_call
                                                        : null)->getHtml()?></td>
                </tr>
            <? endforeach; ?>
            </table>
            <script type="text/javascript">
            emulationRadioForCheckboxesAutoLoad('emulationRadio');
            </script>
        </td>
    </tr>
    <?php endif; ?>
    <tr>
        <td>Телефон:</td>
        <td><?=$this->getHelper('Helper_Form')->inputText('user[phone]', $this->user->getPhone(), array('maxlength'=>255, 'class'=>'textSmall'))->getHtml()?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->phone)?></td>
    </tr>
    <tr>
        <td><?=$this->lang->user_icq?>:</td>
        <td><?=$this->getHelper('Helper_Form')->inputText('user[icq]', $this->user->getIcq(), array('maxlength'=>10,
                                                     'onkeyup'=>'filterFieldDigit(this)',
                                                     'class'=>'textSmall'))->getHtml()?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->icq)?></td>
    </tr>
    <tr>
        <td><?=$this->lang->user_url?>:</td>
        <td><?=$this->getHelper('Helper_Form')->inputText('user[url]', $this->user->getUrl() ? $this->user->getUrl() : 'http://', array('maxlength'=>255, 'class'=>'textSmall'))->getHtml()?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->url)?></td>
    </tr>

    <tr align="center">
        <td colspan="2">
        <?=$this->getHelper('Helper_Form')->inputHidden('user[id]', $this->user->getId())->getHtml()?>
        <?=$this->getHelper('Helper_Form')->inputSubmit('submit', $this->lang->save_changes)->getHtml()?>&nbsp;&nbsp;&nbsp;
        <?=$this->getHelper('Helper_Form')->inputFullCheckbox('return_on_page', 1, 0, $this->return_on_page, array('id'=>'label_return_on_page'))?>
        &nbsp;<?=$this->getHelper('Helper_Form')->Label($this->lang->return_to_this_page, 'label_return_on_page')->getHtml()?>
        </td>
    </tr>
</table></form>
<script type="text/javascript">
// <![CDATA[
try {
    var cform = new checkForm('<?=$this->_module_name?>_<?=$this->_controller_name?>');
    cform.putFocus();
} catch (e) {}

// Отмеченные пользователем города и страны.
// Данный массив нужен для того, что бы можно было по данным значениям
// сделать selected для списков.
var checked_user_locations = new Array();
checked_user_locations['country'] = '<?=$this->user->getCountry()?>';
checked_user_locations['region'] = '<?=$this->user->getRegion()?>';
checked_user_locations['city'] = '<?=$this->user->getCity()?>';

// Массив select-ов в их порядке.
// Данный массив используется в алгоритме функции
locations_chain = new Array('country', 'region', 'city');

locations_create('country', 0);

<? if ($this->user->getCountry()): ?>
locations_create('region', <?=$this->user->getCountry()?>);
<? endif; ?>

<? if ($this->user->getRegion()): ?>
locations_create('city', <?=$this->user->getRegion()?>);
<? endif; ?>
// ]]>
</script>

</body></html>