<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
<meta name="keywords" content="<?=$this->lang['meta']['keywords']?>" />
<meta name="description" content="<?=$this->lang['meta']['description']?>" />
<link rel="stylesheet" href="<?=$this->path['css']?>frontend/main.css" type="text/css" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />
<!--[if IE]>
    <link rel="stylesheet" type="text/css" href="<?=$this->path['css']?>frontend/all-ie.css" />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="<?=$this->path->js?>tooltip.js"></script>
<script type="text/javascript" src="<?=$this->path->js?>jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="<?=$this->path->js?>jquery.corner.js"></script>
<script type="text/javascript" src="<?=$this->path->js?>modules/Common/scripts.js"></script>
<?=$this->getHelper('Html_Title')->getHtml()?>
</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="user_frontend-getpassword" class="content">

<h2 class="header"><?=$this->getHelper('Html_Title')->getByIndex(1)?></h2>

<? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

<form onsubmit="if (typeof cform != 'undefined' && cform) return cform.isEmptyInput()" method="post" action="<?=$this->hsc_request_uri?>">
	<fieldset>
	    <legend>Идентификация пользователя</legend>
	    <?=$this->getHelper('Helper_Form')->getFieldError($this->err['common_error'])?>
	    <div id="left">
	        <p>Если Вы забыли свой логин или пароль, введите какие-либо одни ваши данные, которые Вы указали при регистрации &mdash; логин или email-адрес и нажмите на кнопку &laquo;выслать код подтверждения&raquo;. Если при регистрации в системе Вы указали свой email-адрес, то на него придет письмо с уникальной ссылкой. Пройдя по этой ссылке, Вы подтвердите свою принадлежность к указанному аккаунту и новый пароль будет выслан на Ваш регистрационный почтовый ящик.</p>
	    </div>
	    <div id="right">
			<table>
			    <colgroup>
			        <col width="100" />
			        <col />
			    </colgroup>
			    <tr>
			        <td><strong class="compulsory">Ваш логин:</strong></td>
			        <td><?=$this->getHelper('Helper_Form')->inputText('user[login]', $this->user_login, array('maxlength'=>255, 'id'=>'user_login', 'title'=>'Введите логин Вашего аккаунта', 'class'=>'medium'))->getHtml()?>
			        <?=$this->getHelper('Helper_Form')->getFieldError($this->err->user_login)?></td>
			    </tr>
			    <tr>
			        <td colspan="2">или</td>
			    </tr>
			    <tr>
			        <td><strong class="compulsory">Ваш email:</strong></td>
			        <td><?=$this->getHelper('Helper_Form')->inputText('user[mail]', $this->user_mail, array('maxlength'=>255, 'title'=>'Введите email-адрес Вашего аккаунта', 'class'=>'medium'))->getHtml()?>
			            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->user_mail)?></td>
			    </tr>
			</table>
	    </div>
	</fieldset>

	<div class="submit_block">
	    <?=$this->getHelper('Helper_Form')->inputSubmit('submit', 'Выслать код подтверждения')->getHtml()?>
	</div>
</form>

</div>
<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>
</body></html>