<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru" dir="ltr">
<head>
<?=$this->getHelper('Html_Title')->getHtml()?>
<meta http-equiv="Content-language" content="ru" />
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
<link rel="stylesheet" href="/http/css/backend/main.css" type="text/css" />
</head><body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>
<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="aTable">
<tr><td><a class="add_element" href="/admin/advert/edit/"><?=$this->lang['adding_advert']?></a> <span class="vhr">|</span></td></tr>
</table>

<?
    $navigation_params = array
    (
        'css.normalLinkClass' => 'navigation_normal_link', // CSS-класс гиперссылки.
        'css.activeLinkClass' => '', // CSS-класс открытой в данный момент гиперссылки.
        'GET' => array
        (
            'field_name' => $this->field_name,
            'sort_order' => $this->sort_order,
            'id_category' => $this->id_category,
            'id_user' => $this->id_user
        ),
    );
?>

<? include $this->getRealTemplatePath('Common/BackendNavigation') ?>

<table class="aTable">
<? if ($this->adverts): ?>
    <colgroup>
        <col width="5%" />
        <col width="35%" />
        <col width="20%" />
        <col width="20%" />
        <col width="5%" />
        <col width="5%" />
        <col width="5%" />
        <col width="5%" />
    </colgroup>
    <tr>
      <th colspan="8"><h4><?=$this->lang['list_of_adverts']?></h4></th>
    </tr>
    <tr class="head_params">
    <td>
    <?php
        $linker = $this->getHelper('Helper_SortLink')
                       ->setFieldName('id')
                       ->setAnchor($this->lang['id'])
                       ->setUrl('/admin/advert/')
                       ->setIconSrc('/http/image/system/icon/')
                       ->setCurrentFieldName($this->field_name)
                       ->setCurrentSortOrder($this->sort_order)
                       ->setQueryStringFromArray(array(
                           'sep' => $this->navigation->getCurrentSeparator(),
                           'page' => $this->navigation->getCurrentPage(),
                           'id_category' => $this->id_category,
                           'id_user' => $this->id_user
                           ));

        echo $linker->getHtml();
    ?>
    </td>
    <td>
    <?php
        echo $linker->setFieldName('header')
                    ->setAnchor($this->lang['advert_header'])
                    ->getHtml(); ?>
    </td>
    <td>
    <?php
        echo $linker->setFieldName('category')
                    ->setAnchor($this->lang['advert_category'])
                    ->getHtml(); ?>
    </td>
    <td>
    <?php
        echo $linker->setFieldName('user_name')
                    ->setAnchor($this->lang['advert_user_name'])
                    ->getHtml(); ?>
    </td>
    <td>
    <?php
        echo $linker->setFieldName('view_count')
                    ->setAnchor($this->lang['advert_view_count'])
                    ->getHtml(); ?>
    </td>
    <td>
    <?php
        echo $linker->setFieldName('active')
                    ->setAnchor($this->lang['advert_active'])
                    ->getHtml(); ?>
    </td>
    <td colspan="2"><?=$this->lang['actions']?></td>
    </tr>

    <? foreach($this->adverts as $row):?>
    <tr class="color_hover">
        <td class="center"><?=$row['advert']->getId()?></td>
        <td><p class="small"><?=$row['advert']->getCreateDate()->formatDateForPeople()?></p>
            <p><b><a class="external" target="_blank" href="/categories<?=$row['category']->getUrl()?><?=$row['advert']->getId()?>.xhtml"><?=Helper_Format::hsc($row['advert']->getHeader())?></a></b></p></td>
        <td><a href="?id_category=<?=$row['category']->getId()?>&amp;id_user=<?=$this->id_user?>"><?=$row['category']->getName()?></a></td>
        <td>
        <? if ($row['user']->isGuest()): ?>
            <a href="?id_user=<?=$row['user']->getId()?>&amp;id_category=<?=$this->id_category?>"><?=Helper_Format::hsc($row['user']->getFullNameOrLogin())?></a>
        <? else: ?>
            <? if ($row['advert']->getMainUserName()): ?>
                <a href="?id_user=<?=$row['user']->getId()?>&amp;id_category=<?=$this->id_category?>"><?=Helper_Format::hsc($row['user']->getFullName() ?: $row['advert']->getUserName())?></a>
            <? else: ?>
                <a href="?id_user=<?=$row['user']->getId()?>&amp;id_category=<?=$this->id_category?>"><?=Helper_Format::hsc($row['advert']->getUserName() ?: $row['user']->getFullNameOrLogin())?></a>
            <? endif; ?>
            <span class="lighttext">[<a class="lighttext" href="/admin/user/edit/?id=<?=$row['user']->getId()?>">профиль</a>]</span>
        <? endif; ?>
        </td>
        <td class="center"><?=$row['advert']->getViewCount()?></td>
        <td class="center"><? if($row['advert']->getActive()):?>
                <?=$this->lang['yes']?>
            <? else: ?>
                <span class="lighttext"><?=$this->lang['no']?></span>
            <? endif; ?>
        </td>
        <td class="td_actions"><a href="/admin/advert/edit/?id=<?=$row['advert']->getId()?>&amp;referer=<?=$this->urlencode_full_request_uri?>"><img src="/http/image/system/icon/edit.png" alt="" /></a></td>
        <td class="td_actions">

            <a onclick="return confirm('<?=sprintf($this->lang['question_delete_advert'], $this->getHelper('Helper_Format')->run($row['advert']->getHeader(), 'entDec', 'confirm'))?>')" href="/admin/advert/delete/?id=<?=$row['advert']->getId()?>&amp;referer=<?=$this->urlencode_full_request_uri?>"><img src="/http/image/system/icon/delete.png" alt="" /></a>

        </td>
    </tr>
    <? endforeach; ?>

<? else: ?>
    <tr>
      <th><h4><?=$this->lang['list_of_adverts']?></h4></th>
    </tr>
    <tr class="center"><td><?=$this->lang['empty_list_of_adverts']?></td></tr>
<? endif; ?>
</table>

<? include $this->getRealTemplatePath('Common/BackendNavigation') ?>

</body></html>