<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
<meta name="keywords" content="<?=($this->category->getKeywords()
                                      ? strip_tags($this->category->getKeywords())
                                      : $this->lang['meta']['keywords'])?>" />
<meta name="description" content="<?=($this->category->getDescription()
                                      ? strip_tags($this->category->getDescription())
                                      : $this->lang['meta']['description'])?>" />
<link rel="stylesheet" href="/http/css/frontend/main.css" type="text/css" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />
<!--[if IE]>
    <link rel="stylesheet" type="text/css" href="/http/css/frontend/all-ie.css" />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="/http/js/library/index.js"></script>
<script type="text/javascript" src="/http/js/library/locations.js"></script>
<script type="text/javascript" src="/http/js/tooltip.js"></script>
<script type="text/javascript" src="/http/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/http/js/jquery.corner.js"></script>
<script type="text/javascript" src="/http/js/modules/common/scripts.js"></script>
<?=$this->getHelper('Html_Title')->getHtml()?>
</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="advert_frontend-category-list" class="content">

<h2 class="header">
    <a href="/categories/">Категории</a>
    <?=$this->getHelper('Module_Category_Helper_BreadCrumbs', $this->path_to_category, '/categories')->getHtml()?>
</h2>

<? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

<?php if ($this->subcategories && $this->subcategories->count()): ?>
    <div class="subcategories">
        <h3 class="header">Подкатегории категории &laquo;<?=$this->category->getName()?>&raquo;:</h3>

        <? if ($this->category->getDescription()): ?>
            <div id="category_description"><?=$this->category->getDescription()?></div>
        <? endif;?>

        <?=$this->getHelper('Module_Category_Helper_Subcategories', $this->subcategories, '/categories')->getHtml()?>
    </div>
<?php endif; ?>

<div class="subcategories div-clear">
    <h3 class="header">
        <span title="Фильтр <?=($this->filter_search ? 'включён' : 'выключен. Для включения фильтра отметьте критерии поиска и нажимте кнопку &laquo;Запомнить&raquo;')?>" id="filter_<?=($this->filter_search ? 'online' : 'offline')?>">Фильтр по объявлениям:</span><sup><span title="Фильтрация объявлений позволяет выделить объявления подходящие конкретно вам по географическому признаку, а также по типу сделки. Фильтр запоминает введенные вами настройки и использует их на всех страницах сайта до тех пор, пока вы их не измените. Для работоспособности фильтра не отключайте cookie-файлы в вашем обозревателе." class="help">?</span></sup>
    </h3>

	<form id="filter" method="get" action="<?=$this->hsc_request_uri?>">
	    <table>
	    <tbody>
	        <tr>
	            <td>Вас интересуют:</td>
	            <td>
		            <?php foreach ($this->lang->advert_types_form_2 as $type => $value): ?>
		                <span class="button_switch_advert_type" id="cover_<?=$type?>"><?=$this->getHelper('Helper_Form')->inputRadio('type', $type, $this->type, array('id'=>'label_'.$type))->getHtml()?><?=$this->getHelper('Helper_Form')->Label($value, 'label_'.$type, array('onclick'=>'switch_advert_type(\'cover_'.$type.'\', \'button_switch_advert_type\')'))->getHtml()?></span>
		            <?php endforeach; ?>
		                <span class="button_switch_advert_type" id="cover_"><?=$this->getHelper('Helper_Form')->inputRadio('type', '', (string)$this->type, array('id'=>'label_all'))->getHtml()?><?=$this->getHelper('Helper_Form')->Label('всё', 'label_all', array('onclick'=>'switch_advert_type(\'cover_\', \'button_switch_advert_type\')'))->getHtml()?></span>
	            </td>
	        </tr>
	        <tr>
	            <td>Местоположение:</td>
	            <td>
		            <? $select = $this->getHelper('Helper_Form')->inputSelect('id_country', $this->id_country, array('onchange'=>'locations_next_operation(this)', 'id'=>'country', 'class' => 'form_element_block'));
		               $select->addOption( $this->getHelper('Helper_Form')->inputOption(0, 'не имеет значения', array('style'=>'font-weight:bold; color:#994015;')) );
		            ?>
		            <?=$select->getHtml();?>

		            <? $select = $this->getHelper('Helper_Form')->inputSelect('id_region', $this->id_region, array('onchange'=>'locations_next_operation(this)', 'id'=>'region', 'class' => 'form_element_block', 'style'=>"display:none"));
		               $select->addOption( $this->getHelper('Helper_Form')->inputOption(0, 'не имеет значения', array('style'=>'font-weight:bold; color:#994015;')) );
		            ?>
		            <?=$select->getHtml();?>

		            <?
		            $select = $this->getHelper('Helper_Form')->inputSelect('id_city', $this->id_city, array('onchange'=>'locations_next_operation(this)', 'id'=>'city', 'style'=>"display:none"));
		            $select->addOption( $this->getHelper('Helper_Form')->inputOption(0, 'не имеет значения', array('style'=>'font-weight:bold; color:#994015;')) );
		            ?>
		            <?=$select->getHtml();?>

		            <input type="submit" name="submit" value="запомнить" />
	            </td>
	        </tr>
	    </tbody>
	    </table>
	</form>
</div>

<script type="text/javascript">
//<![CDATA[
window.switch_advert_type = function(id, collection_class_name)
{
    var col = getElementsByTagClassName('span', collection_class_name);

    for (var i=0; i<col.length; i++)
    {
    	col[i].className = collection_class_name;
    }

	document.getElementById(id).className = collection_class_name + ' active';
}

// выделяем при загрузке страницы активный эдемент
window.switch_advert_type('cover_' + '<?=$this->type?>', 'button_switch_advert_type');

var checked_user_locations = new Array();
checked_user_locations['country'] = '<?=$this->id_country?>';
checked_user_locations['region'] = '<?=$this->id_region?>';
checked_user_locations['city'] = '<?=$this->id_city?>';

locations_chain = new Array('country', 'region', 'city');

locations_create('country', 0);

<? if ($this->id_country): ?>
locations_create('region', <?=$this->id_country?>);
locations_visibility('region');
<? endif; ?>

<? if ($this->id_region): ?>
locations_create('city', <?=$this->id_region?>);
locations_visibility('city');
<? endif; ?>
// ]]>
</script>

<?php if($this->adverts && $this->adverts->count()): ?>
	<?php foreach ($this->adverts as $row): ?>
	<div class="advert_cover">
	    <div class="advert_content_outer">
		    <article class="advert_content">
		        <div class="advert_text">
		            <table class="table-structure">
		               <tr>
			               <td colspan="2">
			                   <header>
				                   <h3 class="advert_header">
				                       <a href="/categories<?=$row->category->getUrl()?><?=$row->advert->getId()?>.xhtml" id="advert<?=$row->advert->getId()?>"><?=$this->getHelper('Helper_Format')->userDataOutput($row->advert->getHeader())?></a>
			                       </h3>
		                       </header>
		                   </td>
		                   <td class="right-col" rowspan="<?=$this->subcategories->count() ? 5 : 4?>">
	                            <span class="advert_price space_nowrap">
	                            <?php if (!$row->advert->getPrice()): ?>
	                                <!--noindex-->Договорная<!--/noindex-->
	                            <?php else:?>
	                                <strong><?=number_format($row->advert->getPrice(),0,"."," ")?></strong> <?=$row->advert->getPriceType()->getAsSymbol()?>
	                            <?php endif;?>
	                            </span>
	                        </td>
		               </tr>

	                    <?php if ($row->category->getUrl() !== $this->category_url): ?>
	                    <tr>
	                        <td class="left-col description_td"><!--noindex-->Категория:<!--/noindex--></td>
	                        <td><p><a title="Показать все объявления в категории &laquo;<?=$row->category->getName()?>&raquo;" href="/categories<?=$row->category->getUrl()?>"><?=$row->category->getName()?></a></p></td>
	                    </tr>
	                    <?php endif; ?>

	                   <tr>
	                       <td class="left-col description_td"><!--noindex-->Тип объявления:<!--/noindex--></td>
	                       <td><p><a title="Показать все объявления <?=$this->lang->advert_types_form_3->item($row->advert->getType()->getValue())?> в категории &laquo;<?=$row->category->getName()?>&raquo;" href="/categories<?=$row->category->getUrl()?>?type=<?=$row->advert->getType()->getValue()?>"><?=$row->advert->getType()->getAsText()?></a></p></td>
	                   </tr>

	                    <tr>
				            <td class="left-col description_td"><!--noindex-->Регион:<!--/noindex--></td>
				            <td><p>
				                <?php if ($row->user_city->getId() || $row->user_region->getId() || $row->user_country->getId()): ?>
				                    <? if ($row->user_city->getId()): ?><a title="Показать все объявления <?=$this->lang->advert_types_form_3->item($row->advert->getType()->getValue())?> в категории &laquo;<?=$row->category->getName()?>&raquo; в регионе <?=$row->user_city->getNameRu()?>, <?=$row->user_region->getNameRu()?>, <?=$row->user_country->getNameRu()?>" href="/categories<?=$row->category->getUrl()?>?type=<?=$row->advert->getType()->getValue()?>&amp;id_city=<?=$row->user_city->getId()?>&amp;id_region=<?=$row->user_city->getIdRegion()?>&amp;id_country=<?=$row->user_city->getIdCountry()?>"><?=$row->user_city->getNameRu()?></a>,<?php endif; ?>
				                    <? if ($row->user_region->getId()): ?><a title="Показать все объявления <?=$this->lang->advert_types_form_3->item($row->advert->getType()->getValue())?> в категории &laquo;<?=$row->category->getName()?>&raquo; в регионе <?=$row->user_region->getNameRu()?>, <?=$row->user_country->getNameRu()?>" href="/categories<?=$row->category->getUrl()?>?type=<?=$row->advert->getType()->getValue()?>&amp;id_region=<?=$row->user_region->getId()?>&amp;id_country=<?=$row->user_region->getIdCountry()?>"><?=$row->user_region->getNameRu()?></a>,<?php endif; ?>
				                    <? if ($row->user_country->getId()): ?><a title="Показать все объявления <?=$this->lang->advert_types_form_3->item($row->advert->getType()->getValue())?> в категории &laquo;<?=$row->category->getName()?>&raquo; в регионе <?=$row->user_country->getNameRu()?>" href="/categories<?=$row->category->getUrl()?>?type=<?=$row->advert->getType()->getValue()?>&amp;id_country=<?=$row->user_country->getId()?>"><?=$row->user_country->getNameRu()?></a><?php endif; ?>
				                <?php else: ?>
				                    <!--noindex-->не указан<!--/noindex-->
				                <?php endif; ?>
				            </p></td>
				        </tr>
				        <tr>
	                        <td class="text" colspan="2">
	                            <p>
	                             <?php
							     $advert_text = Helper_Format::getPreviewStr($row->advert->getText(), 200, '...');
							     echo $this->getHelper('Helper_Format')->run($advert_text, 'strip_tags', 'hsc', 'entDec', 'bb2html', 'bb2html2strip');
							     ?>
	                            </p>
	                        </td>
	                    </tr>
		            </table>
		        </div>

                <nav>
			        <ul class="my-adverts--ul-advert-manager">
			            <li class="zoom_link"><a class="space_nowrap" href="/categories<?=$row->category->getUrl()?><?=$row->advert->getId()?>.xhtml">Посмотреть объявление</a></li>
			            <li class="advert_date space_nowrap">
			                <!--noindex-->Размещено:<!--/noindex-->
			                <time datetime="<?=$row->advert->getCreateDate()->format(DateTime::ATOM)?>" pubdate="pubdate"><?=$row->advert->getCreateDate()->formatDateForPeople()?></time></li>
			        </ul>
		        </nav>

		        <div class="div-clear"></div>
		    </article>
	    </div>
	</div>
	<?php endforeach; ?>
<?php else: ?>
	<div class="advert_cover">
	    <div class="advert_content_outer">
	        <article class="advert_content">
	            <div class="advert_text robot">
	                Привет, меня зовут Поисковый Робот.<br /><br />Мне очень не приятно тебе об этом говорить, но в этой категории я ничего не нашел по твоему запросу :(<br />Но это не моя вина, поверь. Просто <em>объявлений, удовлетворяющих критериям поиска</em>, на сайте пока нет.<br /><br />Попробуй <em>изменить параметры фильтра</em> и я обязательно постараюсь найти для тебя что-нибудь хорошее.<br /><br />Обещаю :)
	            </div>

			    <ul class="my-adverts--ul-advert-manager">
			        <li class="advert_date space_nowrap">Попробуйте изменить параметры фильтра</li>
			    </ul>

	            <div class="div-clear"></div>

	        </article>
	    </div>
	</div>
<?php endif; ?>

<?php
$navigation_params = array
(
    'css.normalLinkClass' => 'navigation_normal_link', // CSS-класс гиперссылки.
    'css.activeLinkClass' => 'navigation_open_link', // CSS-класс открытой в данный момент гиперссылки.
    'GET' => array
    (
        'id_city' => $this->id_city,
        'id_region' => $this->id_region,
        'id_country' => $this->id_country,
        'type' => $this->type
    ),
);
?>

<div class="navigation_list">
    Всего объявлений: <strong><?=$this->navigation->getCount()?></strong>
    <? if ($this->navigation->getCount()): ?>
        <br /><br /><span class="navigation_title">Страницы:</span> <?=$this->getHelper('Helper_Navigation', $this->navigation)->getHtml($navigation_params)?>
    <? endif; ?>
</div>

<? if($this->category->getDescription() && !$this->subcategories->count()): ?>
<div id="bottom_annotation"><p><?=$this->category->getDescription()?></p></div>
<? endif; ?>

</div>
<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>
</body></html>