<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru" dir="ltr">
<head>
<?=$this->getHelper('Html_Title')->getHtml()?>
<meta http-equiv="Content-language" content="ru" />
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
<link rel="stylesheet" href="/http/css/backend/main.css" type="text/css" />
<script type="text/javascript" src="/http/js/library/index.js"></script>
</head><body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>

<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="aTable">
<tr><td><a class="add_element" href="/admin/user/edit/"><?=$this->lang->add_user?></a> <span class="vhr">|</span></td></tr>
</table>

<table class="aTable">
<?php if ($this->users && $this->users->count()): ?>
    <colgroup>
        <col width="5%" />
        <col width="20%" />
        <col width="20%" />
        <col width="35%" />
        <col width="5%" />
        <col width="5%" />
    </colgroup>
    <tr>
      <th colspan="6"><h4><?=$this->lang['the_list_of_users']?></h4></th>
    </tr>
    <tr class="head_params">
        <td>
    <?php
        $linker = $this->getHelper('Helper_SortLink')
                       ->setFieldName('id')
				       ->setAnchor($this->lang['id'])
				       ->setUrl('/admin/user/')
				       ->setIconSrc('/http/image/system/icon/')
				       ->setCurrentFieldName($this->field_name)
				       ->setCurrentSortOrder($this->sort_order)
				       ->setQueryStringFromArray(array(
				           'sep' => $this->navigation->getCurrentSeparator(),
					       'page' => $this->navigation->getCurrentPage(),
					       'search' => $this->search,
					       'col' => $this->col,
					       'user_active' => $this->user_active,
					       'user_city' => $this->user_city,
					       'user_region' => $this->user_region,
					       'user_country' => $this->user_country
                           ));

        echo $linker->getHtml();
    ?>
        </td>
        <td>
    <?php
        echo $linker->setFieldName('first_name')
                    ->setAnchor($this->lang['user_first_name'])
                    ->getHtml(); ?>
        </td>
        <td>
    <?php
        echo $linker->setFieldName('ip')
                    ->setAnchor($this->lang['user_ip'])
                    ->getHtml(); ?>
        </td>
        <td><?=$this->lang['place_of_residence']?></td>
        <td colspan="2"><?=$this->lang['actions']?></td>
    </tr>

    <? foreach($this->users as $row): ?>
    <tr class="center color_hover">
        <td><?=$row->user->getId()?></td>
        <td><a href="/admin/user/edit/?id=<?=$row->user->getId()?>"><?=$this->getHelper('Helper_Format')->hsc($row->user->getFullNameOrLogin())?></a></td>
        <td><a href="/admin/user/?search=<?=$row->user->getIp()?>&amp;col=user_ip"><?=$row->user->getIp()?></a></td>
        <td>
        <?php if ($row->user->getCountry()):?>
            <a href="/admin/user/?user_country=<?=$row->user_country->getId()?>"><?=$row->user_country->getNameRu()?></a>,
        <?php endif; ?>
        <?php if($row->user->getRegion()): ?>
            <a href="/admin/user/?user_region=<?=$row->user_region->getId()?>"><?=$row->user_region->getNameRu()?></a>,
        <?php endif; ?>
        <?php if ($row->user->getCity()):?>
            <a href="/admin/user/?user_city=<?=$row->user_city->getId()?>"><?=$row->user_city->getNameRu()?></a></td>
        <?php endif; ?>

        <td class="td_actions"><a href="/admin/user/edit/?id=<?=$row->user->getId()?>&amp;referer=<?=$this->urlencode_full_request_uri?>"><img alt="" src="/http/image/system/icon/edit.png" /></a></td>
        <td class="td_actions">
            <a onclick="return confirm('<?=$this->lang->question_delete_user?> &laquo;<?=$this->getHelper('Helper_Format')->run($row->user->getFullNameOrLogin(), 'entDec', 'confirm')?>&raquo; (id: <?=$row->user->getId()?>)?')" href="/admin/user/delete/?id=<?=$row->user->getId()?>&amp;referer=<?=$this->urlencode_full_request_uri?>"><img src="/http/image/system/icon/delete.png" alt="" /></a>
        </td>
    </tr>
    <? endforeach; ?>

<? else: ?>
    <tr>
      <th><h4><?=$this->lang->the_list_of_users?></h4></th>
    </tr>
    <tr class="center"><td><?=$this->lang->not_found_request_data?></td></tr>
<? endif; ?>
</table>

<?php
    $navigation_params = array
    (
        'css.normalLinkClass' => 'navigation_normal_link', // CSS-класс гиперссылки.
        'css.activeLinkClass' => '', // CSS-класс открытой в данный момент гиперссылки.
        'GET' => array
        (
            'search' => $this->search,
            'col' => $this->col,
            'user_active' => $this->user_active,
            'field_name' => $this->field_name,
            'sort_order' => $this->sort_order,
            'user_city' => $this->user_city,
            'user_region' => $this->user_region,
            'user_country' => $this->user_country
        ),
    );
?>

<? include $this->getRealTemplatePath('Common/BackendNavigation') ?>

    <form id="search_form" action="<?=$this->hsc_request_uri?>" method="get">
    <table class="aTable">
        <colgroup>
            <col width="33%" />
            <col width="33%" />
            <col width="33%" />
        </colgroup>
        <tr>
            <th colspan="3"><h4><?=$this->lang->search_users?></h4></th>
        </tr>
        <tr class="head_params">
            <td><?=$this->lang->what_to_search?></td>
            <td><?=$this->lang->domain_search?></td>
            <td><?=$this->lang->user_activities?></td>
        </tr>
        <tr class="center">
            <td>
                <input type="text" value="<? if($this->search): ?><?=$this->getHelper('Helper_Format')->hsc($this->search)?><? endif; ?>" maxlength="300" name="search" id="search" />
            </td>
            <td>
                <select name="col" class="inputText">
                    <option value="all"<? if(!$this->col): ?> selected="selected"<? endif; ?>>Везде</option>
                    <option value="user_first_name"<? if($this->col=="user_first_name"): ?> selected="selected"<? endif; ?>><?=$this->lang->user_first_name?></option>
                    <option value="user_icq"<? if($this->col=="user_icq"): ?> selected="selected"<? endif; ?>><?=$this->lang->user_icq?></option>
                    <option value="user_url"<? if($this->col=="user_url"): ?> selected="selected"<? endif; ?>><?=$this->lang->user_url?></option>
                    <option value="user_mail"<? if($this->col=="user_mail"): ?> selected="selected"<? endif; ?>><?=$this->lang->user_mail?></option>
                    <option value="user_ip"<? if($this->col=="user_ip"): ?> selected="selected"<? endif; ?>><?=$this->lang->user_ip?></option>
                    <option value="id_user"<? if($this->col=="id_user"): ?> selected="selected"<? endif; ?>><?=$this->lang->id_user?></option>
                </select>
            </td>
            <td>
                <select name="user_active" class="inputText">
                    <option value=""<? if(!$this->user_active): ?> selected="selected"<? endif; ?>><?=$this->lang->any?></option>
                    <option value="1"<? if($this->user_active=='1'): ?> selected="selected"<? endif; ?>><?=$this->lang->active?></option>
                    <option value="0"<? if($this->user_active=='0'): ?> selected="selected"<? endif; ?>><?=$this->lang->blocked?></option>
                </select>
            </td>
        </tr>
        <tr class="center">
            <td colspan="5">
                <input type="submit" value="Поиск" />&nbsp;<input type="submit" class="submit" onclick="clear_form('search_form')" value="Сбросить параметры поиска" />
            </td>
        </tr>
    </table>
    </form>
</body></html>