<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
<meta name="keywords" content="<?=$this->lang['meta']['keywords']?>" />
<meta name="description" content="<?=$this->lang['meta']['description']?>" />
<link rel="stylesheet" href="/http/css/frontend/main.css" type="text/css" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />
<!--[if IE]>
    <link rel="stylesheet" type="text/css" href="/http/css/frontend/all-ie.css" />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="/http/js/tooltip.js"></script>
<script type="text/javascript" src="/http/js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="/http/js/jquery.corner.js"></script>
<script type="text/javascript" src="/http/js/modules/common/scripts.js"></script>
<?=$this->getHelper('Html_Title')->getHtml()?>
</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div class="content">

<h2 class="header"><?=$this->getHelper('Html_Title')->getByIndex(1)?></h2>

<? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

<?=$this->getHelper('Helper_Form')->getFieldError($this->err->common_error)?>

</div>
<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>
</body></html>