<footer>
    <div id="bottom_info">
        <div id="bottom_right_copyright">
        <a href="/help/faq">FAQ</a> |
        <a href="/help/poleznye_sovety">Советы по размещению объявлений</a> |
        <a href="/help/terms_of_service">Соглашение об условиях использования</a> |
        <a href="/help/about">О сайте</a></div>
        <div id="bottom_left_copyright"><a style="text-decoration:none"  href="http://<?=$_SERVER['HTTP_HOST']?>"><?=$_SERVER['HTTP_HOST']?></a>&nbsp;<?=date('Y')?></div>
    </div>

    <div id="bottom_buttons">
       <!--LiveInternet counter--><script type="text/javascript"><!--
document.write("<a href='http://www.liveinternet.ru/click' "+
"target=_blank><img src='//counter.yadro.ru/hit?t57.6;r"+
escape(document.referrer)+((typeof(screen)=="undefined")?"":
";s"+screen.width+"*"+screen.height+"*"+(screen.colorDepth?
screen.colorDepth:screen.pixelDepth))+";u"+escape(document.URL)+
";h"+escape(document.title.substring(0,80))+";"+Math.random()+
"' alt='' "+
"border='0' width='88' height='31'><\/a>")
//--></script><!--/LiveInternet-->

<!-- Rating@Mail.ru counter -->
<script type="text/javascript">//<![CDATA[
var a='';js=10;d=document;
try{a+=';r='+escape(d.referrer);}catch(e){}try{a+=';j='+navigator.javaEnabled();js=11;}catch(e){}
try{s=screen;a+=';s='+s.width+'*'+s.height;a+=';d='+(s.colorDepth?s.colorDepth:s.pixelDepth);js=12;}catch(e){}
try{if(typeof((new Array).push('t'))==="number")js=13;}catch(e){}
try{d.write('<a href="http://top.mail.ru/jump?from=1876458"><img src="http://d1.ca.bc.a1.top.mail.ru/counter?id=1876458;t=230;js='+js+
a+';rand='+Math.random()+'" alt="Рейтинг@Mail.ru" style="border:0;" height="31" width="88" \/><\/a>');}catch(e){}//]]></script>
<noscript><p><a href="http://top.mail.ru/jump?from=1876458"><img src="http://d1.ca.bc.a1.top.mail.ru/counter?js=na;id=1876458;t=230"
style="border:0;" height="31" width="88" alt="Рейтинг@Mail.ru" /></a></p></noscript>
<!-- //Rating@Mail.ru counter -->

<!-- begin of Top100 code -->
<script id="top100Counter" type="text/javascript" src="http://counter.rambler.ru/top100.jcn?2290987"></script>
<noscript>
<a href="http://top100.rambler.ru/navi/2290987/">
<img src="http://counter.rambler.ru/top100.cnt?2290987" alt="Rambler's Top100" />
</a>
</noscript>
<!-- end of Top100 code -->

<!--noindex-->
<a rel="nofollow" href="http://validator.w3.org/check?uri=referer"><img src="/http/image/desing/icon/html5valid.gif" alt="Adverts.ru следует стандартам World Wide Web Consortium" title="Adverts.ru следует стандартам World Wide Web Consortium" /></a>
<!--/noindex-->
    </div>
</footer>

<!-- <?=$this->_module_name?>_<?=$this->_controller_name?> -->