<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
<meta name="keywords" content="<?=$this->lang['meta']['keywords']?>" />
<meta name="description" content="<?=$this->lang['meta']['description']?>" />
<link rel="stylesheet" href="<?=$this->path['css']?>frontend/main.css" type="text/css" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />
<!--[if IE]>
    <link rel="stylesheet" type="text/css" href="<?=$this->path['css']?>frontend/all-ie.css" />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="<?=$this->path['js']?>tooltip.js"></script>
<script type="text/javascript" src="<?=$this->path['js']?>jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="<?=$this->path['js']?>jquery.corner.js"></script>
<script type="text/javascript" src="<?=$this->path['js']?>modules/Common/scripts.js"></script>
<?=$this->getHelper('Html_Title')->getHtml()?>
</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div id="category_frontend-categories-list" class="content">

<h2 class="header"><?=$this->lang->title->item(1)?></h2>

<? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

<?php $count = ceil($this->categories->count()/3); ?>
<table id="categories_list">
<tr>
<?php for ($i=0; $i<3; $i++): ?>
    <td>
        <?php for ($j=0; $j<$count; $j++): $index = $i+$j+$i*($count-1); ?>
            <?php if ($this->categories->item($index)): ?>
                <a class="index_h3 space_nowrap" href="/categories<?=$this->categories->item($index)->getUrl()?>"><?=$this->categories->item($index)->getName()?></a>
            <?php endif; ?>
        <?php endfor; ?>
    </td>
<?php endfor; ?>
</tr>
</table>
</div>

<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>

</body></html>