<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru" dir="ltr">
<head>
<?=$this->getHelper('Html_Title')->getHtml()?>
<meta http-equiv="Content-language" content="ru" />
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
<link rel="stylesheet" href="/http/css/backend/main.css" type="text/css" />
</head><body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>

<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<form id="<?=$this->_module_name?>_<?=$this->_controller_name?>" method="post" action="<?=$this->hsc_request_uri?>" onsubmit="if(typeof cform != 'undefined') return cform.isEmptyThisFields()">
<table class="aTable">
    <colgroup>
        <col width="40%" />
        <col width="60%" />
    </colgroup>
    <tr>
        <th colspan="2"><h4>
            <? if($this->group->getId()): ?>
                <?=$this->lang['editing_the_group']?> &laquo;<?=$this->getHelper('Helper_Format')->run($this->group->getName(), 'entDec', 'hsc');?>&raquo;
            <? else: ?>
                <?=$this->lang['adding_group']?>
            <? endif; ?></h4>
        </th>
    </tr>
    <tr>
        <td><strong class="compulsory"><?=$this->lang['group_name']?>:</strong></td>
        <td><?=$this->getHelper('Helper_Form')->inputText('group[name]', $this->group->getName(), array('maxlength'=>255, 'class'=>'textLarge'))->getHtml()?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->name)?></td>
    </tr>
    <tr>
        <td><strong class="compulsory"><?=$this->lang['group_alias']?>:</strong></td>
        <td><?=$this->getHelper('Helper_Form')->inputText('group[alias]', $this->group->getAlias(), array('maxlength'=>30, 'class'=>'textLarge'))->getHtml()?>
            <?=$this->getHelper('Helper_Form')->getFieldError($this->err->alias)?></td>
    </tr>
    <tr>
        <td><strong class="compulsory">Группа активна:</strong></td>
        <td>
        <?
        $select = $this->getHelper('Helper_Form')->inputSelect('group[active]', $this->group->getActive());
        $select->addOption( $this->getHelper('Helper_Form')->inputOption(1, $this->lang['yes']) );
        $select->addOption( $this->getHelper('Helper_Form')->inputOption(0, $this->lang['no']) );
        echo $select->getHtml();
        ?>
        <?=$this->getHelper('Helper_Form')->getFieldError($this->err->active)?>
        </td>
    </tr>
    <tr>
        <td><strong class="compulsory"><?=$this->lang['group_actions']?>:</strong></td>
        <td>
            <? foreach($this->modules as $module): ?>

            <fieldset class="actions">
                <legend class="action_list"><strong><?=$module->getName()?></strong></legend>

                <? if ($module->getControllers() && $module->getControllers()->count()): ?>
                <div class="operationsList">
                    <? foreach($module->getControllers() as $controller): ?>
                    <div>
                    <?=$this->getHelper('Helper_Form')->inputFullCheckbox
                    ('group[group_access]['.$module->getId().']['.$controller->getId().']',
                     1, 0, $this->group->getAcccessForController($controller),
                     array('class' => 'action_'.$controller->getId(),
                           'id'=>'label_' . $module->getId() . '_' . $controller->getId()
                          )
                    )?>
                    <?=$this->getHelper('Helper_Form')->Label($controller->getName(), 'label_'.$module->getId().'_'.$controller->getId())->getHtml()?>
                    </div>
                    <? endforeach; ?>
                </div>
                <? endif; ?>
            </fieldset>

            <? endforeach; ?>
        </td>
    </tr>
    <tr align="center">
        <td colspan="2">
            <?=$this->getHelper('Helper_Form')->inputHidden('group[id]', $this->group->getId())->getHtml()?>
            <?=$this->getHelper('Helper_Form')->inputSubmit('submit', $this->lang['save_changes'])->getHtml()?>&nbsp;&nbsp;&nbsp;
        <?=$this->getHelper('Helper_Form')->inputFullCheckbox('return_on_page', 1, 0, $this->return_on_page, array('id'=>'label_return_on_page'))?>
        &nbsp;<?=$this->getHelper('Helper_Form')->Label($this->lang['return_to_this_page'], 'label_return_on_page')->getHtml()?>
        </td>
    </tr>
</table></form>

<script type="text/javascript">
// <![CDATA[
try {
    var cform = new checkForm('<?=$this->_module_name?>_<?=$this->_controller_name?>');
    cform.putFocus();
} catch (e){}
// ]]>
</script>
</body></html>