<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ru" lang="ru" dir="ltr">
<head>
<?=$this->getHelper('Html_Title')->getHtml()?>
<meta http-equiv="Content-language" content="ru" />
<meta http-equiv="Content-Type" content="text/html; charset=windows-1251" />
<link rel="stylesheet" href="/http/css/backend/main.css" type="text/css" />

</head><body>

<? include $this->getRealTemplatePath('Common/BackendNotification') ?>


<? include $this->getRealTemplatePath('Common/BackendMenu') ?>

<table class="aTable">
<tr><td><a href="/admin/module/"><?=$this->getHelper('Html_Title')->getByIndex(1)?></a></td></tr>
<tr><td><a class="add_element" href="/admin/module/edit/"><?=$this->lang['add_module']?></a> <span class="vhr">|</span></td></tr>
</table>

<table class="aTable">
<? if ($this->modules->count()): ?>
    <colgroup>
        <col width="5%" />
        <col width="35%" />
        <col width="20%" />
        <col width="20%" />
        <col width="10%" />
        <col width="10%" />
    </colgroup>
    <tr>
      <th colspan="6"><h4><?=$this->lang['list_of_modules']?></h4></th>
    </tr>
    <tr class="head_params">
    <td>
    <?php
        $linker = $this->getHelper('Helper_SortLink')
                       ->setFieldName('id')
                       ->setAnchor($this->lang['id'])
                       ->setUrl('/admin/module/')
                       ->setIconSrc('/http/image/system/icon/')
                       ->setCurrentFieldName($this->field_name)
                       ->setCurrentSortOrder($this->sort_order)
                       ->setQueryStringFromArray(array(
                           //'sep' => $this->navigation->getCurrentSeparator(),
                           //'page' => $this->navigation->getCurrentPage(),
                           ));

        echo $linker->getHtml();
    ?>
    </td>
    <td>
    <?php
        echo $linker->setFieldName('name')
                    ->setAnchor($this->lang['module_name'])
                    ->getHtml(); ?>
    </td>
    <td>
    <?php
        echo $linker->setFieldName('key')
                    ->setAnchor($this->lang['module_key'])
                    ->getHtml(); ?>
    </td>
        <td><?=$this->lang['controllers_count']?></td>
        <td colspan="2"><?=$this->lang['actions']?></td>
    </tr>

    <? foreach ($this->modules as $module): ?>
    <tr class="center color_hover">
        <td><?=$module->getId()?></td>
        <td><?=$this->getHelper('Helper_Format')->run($module->getName())?></td>
        <td><?=$module->getKey()?></td>
        <td>
            <? if ($module->getControllers()->count()): ?>
                <?=$module->getControllers()->count()?> <?=$this->getHelper('Helper_Format')->triumviratForm($module->getControllers()->count(), $this->lang['triumvirat_controllers'])?>
            <? else: ?>
                контроллеров нет
            <? endif; ?>
        </td>
        <td class="td_actions"><a href="/admin/module/edit/?id=<?=$module->getId()?>"><img src="/http/image/system/icon/edit.png" alt="" /></a></td>
        <td class="td_actions">
            <a onclick="return confirm('<?=sprintf(
                                          $this->lang['question_delete_module'],
                                          $this->getHelper('Helper_Format')->confirm($module->getName()),
                                          $module->getId())
                                        ?>')" href="/admin/module/delete/?id=<?=$module->getId()?>&amp;referer=<?=$this->urlencode_full_request_uri?>"><img src="/http/image/system/icon/delete.png" alt="" /></a>
        </td>
    </tr>
    <? endforeach; ?>

<? else: ?>
    <tr>
      <th><h4><?=$this->lang['list_of_modules']?></h4></th>
    </tr>
    <tr class="center"><td><?=$this->lang['not_found_request_data']?></td></tr>
<? endif; ?>
</table>

<?  /*
    $navigation_params = array
    (
        'css.normalLinkClass' => 'navigation_normal_link', // CSS-класс гиперссылки.
        'css.activeLinkClass' => '', // CSS-класс открытой в данный момент гиперссылки.
        'GET' => array
        (
            'field_name' => $this->field_name,
            'sort_order' => $this->sort_order,
        ),
    ); */
?>

<? //include $this->getRealTemplatePath('Common/BackendNavigation') ?>

</body></html>