<table class="aTable">
<tr>
    <td><a style="float:right" href="/logout/?referer=/admin/">Выход из системы</a>
        <div>
            <a href="/admin/advert/">Объявления</a> <span class="vhr">|</span>
            <a href="/admin/user/">Пользователи</a> <span class="vhr">|</span>
            <a href="/admin/group/">Административные группы</a> <span class="vhr">|</span>
            <a href="/admin/module/">Модули</a> <span class="vhr">|</span>
            <a href="/admin/category/">Категории</a> <span class="vhr">|</span>
        </div>
    </td>
</tr>
</table>