<!DOCTYPE html>
<html lang="ru">
<head>
<meta http-equiv="content-type" content="text/html; charset=windows-1251" />
<meta name="keywords" content="<?=$this->lang['meta']['keywords']?>" />
<meta name="description" content="<?=$this->lang['meta']['description']?>" />
<link rel="stylesheet" href="<?=$this->path['css']?>frontend/main.css" type="text/css" />
<link rel="shortcut icon" sizes="16x16" href="/favicon.ico" />
<!--[if IE]>
    <link rel="stylesheet" type="text/css" href="<?=$this->path['css']?>frontend/all-ie.css" />
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script type="text/javascript" src="<?=$this->path['js']?>tooltip.js"></script>
<script type="text/javascript" src="<?=$this->path['js']?>jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="<?=$this->path['js']?>jquery.corner.js"></script>
<script type="text/javascript" src="<?=$this->path['js']?>modules/Common/scripts.js"></script>
<?=$this->getHelper('Html_Title')->add('О сайте')->getHtml()?>
</head><body>

<? include $this->getRealTemplatePath('Common/FrontendTop') ?>

<div class="content">
<? include $this->getRealTemplatePath('Common/FrontendNotification') ?>

    <h2 class="header">О сайте</h2>

    <article id="help">
		<p><strong>Сайт бесплатных объявлений</strong> <a class="text_logo_cover" href="http://www.adverts.ru/"><span class="tl_a">a</span><span class="tl_d">d</span><span class="tl_v">v</span><span class="tl_e">e</span><span class="tl_r">r</span><span class="tl_t">t</span><span class="tl_s">s</span><span class="tl_dot">.</span><span class="tl_r2">r</span><span class="tl_u">u</span></a> появился после того, как нами было потрачено огромное количество времени на поиск бесплатной доски объявлений, отвечающей требованиям простоты размещения информации, отсутствия обязательной регистрации на сайте, удобной и логически понятной структуры категорий, эффективности поиска любых тематических объявлений на сайте. Т.е. сайтa, позволяющего пользователю свободно ориентироваться в огромном постоянно растущем количестве предложений.</p>

		<p>Наш сайт представляет собой электронную доску объявлений, которая поделена на несколько <a href="/categories/">тематических категорий</a>, согласно содержанию самых предложений. Это сайт, где каждый желающий может вывесить своё объявление, а все посетители сайта — прочитать его. </p>
		<p>Для размещения объявлений доступны следующие категории:

		<?php foreach($this->categories as $category): ?>
		    <a href="/categories<?=$category->getUrl()?>"><?=$category->getName()?></a>,
		<?php endforeach; ?></p>

		<p>Таким образом, на сайте бесплатных объявлений <a class="text_logo_cover" href="http://www.adverts.ru/"><span class="tl_a">a</span><span class="tl_d">d</span><span class="tl_v">v</span><span class="tl_e">e</span><span class="tl_r">r</span><span class="tl_t">t</span><span class="tl_s">s</span><span class="tl_dot">.</span><span class="tl_r2">r</span><span class="tl_u">u</span></a> вы можете абсолютно <strong>бесплатно подать объявление</strong> о покупке и продаже автомобиля, можете опубликовать предложение о продаже недвижимости или избавиться от старого ноутбука. Для этого надо всего лишь нажать на ссылку  «<a href="/add.xhtml">Подать объявление</a>», заполнить форму и ждать отклика!</p>
		<p>На сайте мы постарались учесть все нюансы и негативный опыт использования досок и сайтов бесплатных объявлений и надеемся, что <a class="text_logo_cover" href="http://www.adverts.ru/"><span class="tl_a">a</span><span class="tl_d">d</span><span class="tl_v">v</span><span class="tl_e">e</span><span class="tl_r">r</span><span class="tl_t">t</span><span class="tl_s">s</span><span class="tl_dot">.</span><span class="tl_r2">r</span><span class="tl_u">u</span></a> оправдает все ваши ожидания и превратит процесс размещения объявления из утомительного и долгого занятия в дело нескольких минут!</p>
    </article>
</div>
<? include $this->getRealTemplatePath('Common/FrontendBottom') ?>
</body></html>